image: python:3.6-alpine

stages:
  - deploy-dev
  - deploy-production

.deploy: &deploys
  before_script:
    - apk update && apk upgrade
    - apk add nodejs npm
    - npm install -g serverless
    - cd api/
    - npm install
  script:
    - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile bubblecheck
    - serverless deploy --stage ${SLS_ENVIRONMENT}

deploy-dev:
  <<: *deploys
  stage: deploy-dev
  variables:
    SLS_ENVIRONMENT: dev

deploy-prod:
  <<: *deploys
  stage: deploy-production
  variables:
    SLS_ENVIRONMENT: production
  when: manual
