image: alpine:latest

stages:
  - deploy-dev
  - deploy-production

.deploy: &deploys
  before_script:
    - echo "Hello"
  script:
    - echo "In the script for ${SLS_ENVIRONMENT}"

deploy-dev:
  <<: *deploys
  stage: deploy-dev
  variables:
    SLS_ENVIRONMENT: dev

deploy-prod:
  <<: *deploys
  stage: deploy-production
  variables:
    SLS_ENVIRONMENT: production
  when: manual
