image: "docker.io/taylorreece/bc-build-server:latest"

stages:
  - tests
  - deploy-dev
  - deploy-production

web-tests:
  stage: tests
  before_script:
    - cd web/
    - npm i
    - cd ..
  script:
    - cd web/
    - npm run lint

.deploy: &deploys
  before_script:
    - cd web/
    - npm i
    - cd ../api/
    - npm i
    - cd ..
  script:
    - cd web/
    - npm run-script build
    - cd ../api
    - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile bubblecheck
    - serverless deploy --stage ${SLS_ENVIRONMENT}

deploy-dev:
  <<: *deploys
  stage: deploy-dev
  variables:
    SLS_ENVIRONMENT: dev
    AWS_DEFAULT_REGION: us-east-1
  needs: ['web-tests']

deploy-prod:
  <<: *deploys
  stage: deploy-production
  variables:
    SLS_ENVIRONMENT: production
    AWS_DEFAULT_REGION: us-east-1
  when: manual
  needs: ['web-tests']

