image: node:latest

stages:
  - deploy-dev
  - deploy-production

.deploy: &deploys
  before_script:
    - cd api/
    - npm install
  script:
    - serverless deploy --stage ${SLS_ENVIRONMENT}

deploy-dev:
  <<: *deploys
  stage: deploy-dev
  variables:
    SLS_ENVIRONMENT: dev

deploy-prod:
  <<: *deploys
  stage: deploy-production
  variables:
    SLS_ENVIRONMENT: production
  when: manual
