image: python:3.6-alpine

stages:
  - deploy-dev
  - deploy-production

.deploy: &deploys
  before_script:
    - apk update && apk upgrade
    - apk add bash nodejs npm
    - npm install -g serverless
    - pip install awscli
    - cd web/
    - npm i
    - cd ../api/
    - npm i
  script:
    - serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY} --profile bubblecheck
    # - serverless deploy --stage ${SLS_ENVIRONMENT}
    - cd ..
    - bash deploy_react.sh ${SLS_ENVIRONMENT}  

deploy-dev:
  <<: *deploys
  stage: deploy-dev
  variables:
    SLS_ENVIRONMENT: dev
    AWS_DEFAULT_REGION: us-east-1

deploy-prod:
  <<: *deploys
  stage: deploy-production
  variables:
    SLS_ENVIRONMENT: production
    AWS_DEFAULT_REGION: us-east-1
  when: manual
