version: '2'

services:
  api:
    restart: always
    build: ./api
    environment:
      - FLASK_DEBUG=true
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://bubblecheck_user:1234@postgres/bubblecheck_db
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - migrate_and_seed

  migrate_and_seed:
    build: ./api
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://bubblecheck_user:1234@postgres/bubblecheck_db
    depends_on:
      - postgres
    entrypoint: sh
    command: migrate_and_seed.sh

  postgres:
    restart: always
    build: ./postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
