version: '3'

services:
  api:
    restart: always
    build: ./api
    environment:
      - FLASK_DEBUG=true
      - DATABASE_DRIVER=postgresql+psycopg2
      - DATABASE_USER=bubblecheck_user
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=bubblecheck_db
      - DATABASE_ENDPOINT=postgres
      - DATABASE_PORT=5432
      - COGNITO_URL=$COGNITO_URL
      - COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
    ports:
      - "5000:5000"
    volumes:
      - "$PWD_FULL_PATH/api:/app"
    depends_on:
      - postgres
      - migrate_and_seed

  migrate_and_seed:
    build: ./api
    environment:
      - DATABASE_DRIVER=postgresql+psycopg2
      - DATABASE_USER=bubblecheck_user
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=bubblecheck_db
      - DATABASE_ENDPOINT=postgres
      - DATABASE_PORT=5432
    depends_on:
      - postgres
    entrypoint: sh
    command: migrate_and_seed.sh

  postgres:
    restart: always
    build: ./docker/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
