version: '3'

services:
  api:
    restart: always
    build: ./api
    environment:
      - FLASK_DEBUG=true
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - DYNAMO_TABLE=bubblecheck
      - COGNITO_URL=$COGNITO_URL
      - COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
      - AWS_REGION=local
      - AWS_ACCESS_KEY_ID=dummy-access-key
      - AWS_SECRET_ACCESS_KEY=dummy-access-key-secret
      - LOCAL_REACT_HOST=web:3000
    ports:
      - "5000:5000"
    volumes:
      - "$PWD_FULL_PATH/api:/app"
    depends_on:
      - dynamodb
      - dynamodb-table-create

  dynamodb-table-create:
    build: ./docker/dynamodb-table-create
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - DYNAMO_TABLE=bubblecheck
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar

  # For viewing dynamodb tables; accessible at localhost:8001
  dynamodb-admin:
    restart: always
    build: ./docker/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    ports:
      - "8001:8001"
    expose:
      - "8001"

  dynamodb:
    restart: always
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

  web:
    restart: always
    build: ./web
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensure the container sees local file changes
    ports:
      - "3000:3000"
    volumes:
      - "$PWD_FULL_PATH/web/src:/app/src"
