Resources:
  JumpHostSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all outbound traffic, no inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 96.2.242.131/32 # Taylor office
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: 24.220.198.197/32 # Taylor home
          FromPort: 22
          ToPort: 22
      VpcId:
        Ref: Vpc
        
  JumpHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:  ami-04b9e92b5572fa0d1 # Ubuntu 18.04 us-east-1
      KeyName: taylor-laptop
      InstanceType: t3.nano
      SubnetId:
        Ref: PublicSubnet1
      SecurityGroupIds:
        - Fn::GetAtt: [JumpHostSecurityGroup, GroupId]
        - Fn::GetAtt: [LambdaSecurityGroup, GroupId]