"""empty message

Revision ID: 1e39d234c71c
Revises: 85bb8067d85f
Create Date: 2019-02-23 14:01:49.503892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e39d234c71c'
down_revision = '85bb8067d85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentexams',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('exams_id', sa.Text(), nullable=True),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exams_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentexams')
    # ### end Alembic commands ###
