"""Index users email and public uuid

Revision ID: 652ee4d43505
Revises: 2aecebdb8223
Create Date: 2018-06-21 21:34:06.022537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652ee4d43505'
down_revision = '2aecebdb8223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_uuid'), 'users', ['public_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###
