"""Added exam_format column.

Revision ID: 85bb8067d85f
Revises: 0217364e3a53
Create Date: 2018-09-28 10:22:00.388528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bb8067d85f'
down_revision = '0217364e3a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('exam_format', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'exam_format')
    # ### end Alembic commands ###
