"""empty message

Revision ID: 947494356e5c
Revises: 807084ffb319
Create Date: 2018-06-14 23:03:57.191378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947494356e5c'
down_revision = '807084ffb319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['public_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
